inicios_caminho = [
    "Você avança por entre as sombras e encontra",
    "A trilha escurece... e você encontra",
    "O vento sussurra segredos antigos e você encontra",
    "O solo range sob seus pés quando você encontra",
    "Luzes distorcidas dançam ao longe... você encontra",
    "A névoa se parte lentamente, revelando",
    "O cheiro de sangue e ferrugem guia você até",
    "Entre árvores retorcidas e raízes podres, surge",
    "Sons guturais ecoam ao redor quando você encontra",
    "O silêncio repentino anuncia a presença de",
    "As sombras ganham forma e te conduzem até",
    "Uma risada abafada se dissolve no vento quando você encontra",
    "Sangue seco marca o caminho até",
    "Estátuas quebradas observam enquanto você encontra",
    "Uma presença antiga pesa sobre o ar... algo se aproxima",
    "Chamas verdes tremeluzem no escuro, revelando",
    "O céu sem cor parece afundar quando você encontra",
    "Um sussurro em uma língua esquecida te leva até",
    "O tempo parece parar diante de",
    "Sussurros em línguas extintas celebram a chegada de",
    "O passado e o futuro colapsam diante de",
    "As ruínas cantam em agonia ao mostrar",
    "Fragmentos de memórias antigas te trazem até",
    "Garras de sombras te empurram para",
    "A quietude sepulcral é quebrada por",
    "O céu geme em tormento quando você encontra",
    "A noite viva sussurra e surge",
    "Uma presença que não pertence a este mundo revela",
    "As estrelas mortas observam enquanto surge",
    "As paredes do mundo rangem revelando",
    "O chão se abre em carne viva revelando",
    "A poeira ancestral se ergue para formar",
    "As raízes do mundo expõem",
    "O véu entre mundos se rasga, expondo",
    "Rostos perdidos no nevoeiro te olham de dentro de",
    "O ar pesa como chumbo e revela",
    "Cicatrizes no tempo se abrem diante de",
    "As chamas do esquecimento dançam ao redor de",
    "O abismo sorri e apresenta",
    "As paredes respiram quando surge",
    "O tempo ruge ao seu redor quando encontra",
    "O esquecimento sussurra seu nome quando você encara",
    "Estalidos no escuro anunciam",
    "A essência do medo toma forma em",
    "A carne do mundo pulsa revelando",
    "A penumbra viva se afasta, revelando",
    "As vozes dos condenados indicam",
    "As árvores sangram quando você se aproxima de",
    "As sombras costuram seu destino ao encontrar",
    "O frio ancestral do abismo te congela ao encarar",
    "O frio das eras perdidas congela a visão de",
    "O céu despedaçado cospe",
    "A realidade se estilhaça, revelando",
    "A morte caminha ao seu lado até",
    "A eternidade se curva diante de",
    "Os sinos do esquecimento tocam e anunciam",
    "Um sussurro vindo do além conduz até",
    "A noite chora sangue antes que você veja",
    "Olhos invisíveis se abrem e observam",
    "A ruína te chama e te mostra",
    "Ecos de lamentos esquecidos te levam até",
    "O destino empalidece diante de",
    "O breu absoluto te guia até",
    "Fungos brilhantes iluminam o caminho até",
    "A terra corrompida pulsa sob seus pés, revelando",
    "Uma canção espectral ecoa e revela",
    "Os portões do impossível se entreabrem e mostram",
    "As chamas negras iluminam",
    "A fome do vazio se materializa em"
]

inimigos_frases = [
    "um conjunto de peças corrompidas que se movem como se guiadas por ódio.",
    "ecos do tabuleiro que se materializam em figuras hostis.",
    "figuras distorcidas, lembranças quebradas dos antigos jogadores.",
    "silhuetas de antigos campeões caídos que agora servem às trevas.",
    "a tropa de espectros estrategicamente posicionada para te cercar.",
    "movimentos coordenados no escuro... o inimigo preparou seu avanço.",
    "marcas no chão se alinham e ganham forma, revelando o cerco.",
    "as peças adormecidas despertam com rangidos secos e te cercam.",
    "o som metálico de armaduras oculta a aproximação do enxame inimigo.",
    "o tabuleiro sussurra jogadas perdidas... e elas se erguem contra você.",
    "ecos do primeiro jogo voltam à vida... com sede de sangue.",
    "as colunas ao redor ganham olhos e pés... e formam a linha de ataque.",
    "estratégias esquecidas ganham corpo... e sede de vingança.",
    "uma formação precisa se ergue das sombras para te aniquilar.",
    "passos cadenciados denunciam a chegada do próximo lance das trevas.",
    "o sussurro da torre anuncia a abertura do flanco inimigo.",
    "o chão racha em linhas perfeitas... como um xeque prestes a ser dado.",
    "uma emboscada coordenada como um gambito sinistro te envolve.",
    "fileiras de presenças vazias marcham, obedecendo um rei invisível.",
    "os ecos da última partida perdida retornam... com fúria renovada.",
    "as peças esquecidas do tabuleiro se reagrupam, sedentas por revanche.",
    "uma sombra maior move os peões como dedos em marionetes podres.",
    "a atmosfera pesa... o inimigo avança com ordem e crueldade.",
    "linhas e diagonais se alinham com precisão assassina.",
    "os lances do passado ecoam agora em carne e aço, prontos para punir.",
    "o chão emite um pulsar... uma abertura foi ativada contra você.",
    "as casas escuras se fundem e transformam-se em caçadores silenciosos.",
    "o xeque do silêncio traz com ele as peças da execução.",
    "um flanco inimigo inteiro se materializa diante de você.",
    "peças exiladas, esquecidas no abismo, retornam com ódio.",
    "movimentos imperceptíveis desenham o cerco à sua frente.",
    "a simetria cruel do tabuleiro ganha vida em hostilidade pura.",
    "a primeira linha de batalha se ergue, afiada como intenções antigas.",
    "a sombra de um rei caído envia seus lacaios num avanço coordenado.",
    "as peças já estavam em jogo… você apenas não via.",
    "as casas alternadas se tornam olhos atentos... e braços armados.",
    "uma nova partida começa... mas não há regras dessa vez.",
    "os ecos de um xeque-mate maldito sussurram seu nome.",
    "peões se movem de forma errada... como se possuídos por outra lógica.",
    "alguém fez um lance ousado... e a resposta se forma diante de você.",
    "o jogo volta ao início, mas as peças já estão quebradas e furiosas.",
    "a movimentação do inimigo revela sua intenção assassina.",
    "o tempo se dobra e uma partida ancestral se refaz ao seu redor.",
    "a partida interrompida por séculos agora continua... com você no meio.",
    "as diagonais sussurram... e se transformam em lanças vivas.",
    "uma aura púrpura cobre o tabuleiro e arrasta consigo a vanguarda do mal.",
    "você pisou em uma jogada planejada muito antes do seu nascimento.",
    "a ordem do tabuleiro se desfaz... o caos inimigo se reorganiza.",
    "o som de peças caindo ressoa como tambores de guerra.",
    "cada movimento que você faz parece convocar uma resposta assassina.",
    "as peças negras estão em posição... e você é o alvo da vez."
]
